name: telling_logger
description: Comprehensive crash reporting, error tracking, and analytics SDK for Flutter applications. Track errors, monitor performance, and gain insights into your app's behavior.
version: 1.2.2
homepage: https://github.com/ThatSaxyDev/telling-logger
repository: https://github.com/ThatSaxyDev/telling-logger
issue_tracker: https://github.com/ThatSaxyDev/telling-logger/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^12.2.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:

